name: clima
description: A new Flutter application.

publish_to: 1.0.0+1

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  geolocator: ^3.0.1
  http: ^0.12.1
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
      - asset: fonts/SpartanMB-Black.otf
        weight: 900

